apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: laz1e/hello:latest
# Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
# The port that the container is running on in the cluster
